name: SLS Deploy

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test
        env:
          TOOGOODTOGO_EMAIL: ${{ secrets.TOOGOODTOGO_EMAIL }}
          TOOGOODTOGO_PASSWORD: ${{ secrets.TOOGOODTOGO_PASSWORD }}
